import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/app/components/theme-provider";
import DashboardLayout from "@/app/components/dashboard-layout";
import { Toaster } from "@/components/ui/sonner";
import React, { ReactNode } from "react";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout ({
	                                    children,
                                    }: Readonly<{
	children: ReactNode;
}>) {
	return (
		<>
			<html lang="en" suppressHydrationWarning>
			<body
				className={`antialiased h-screen`}
			>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<DashboardLayout>
					{children}
					<Toaster />
				</DashboardLayout>
			</ThemeProvider>
			</body>
			</html>
		</>
	);
}
