import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/app/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import React, { ReactNode } from "react";
import { createClient } from "@/lib/supabase/server";
import Header from "@/app/components/header";
import { AppSidebar } from "@/app/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout ({
	                                    children,
                                    }: Readonly<{
	children: ReactNode;
}>) {

	const supabase = await createClient();
	const {data: {user}} = await supabase.auth.getUser();

	return (
		<>
			<html lang="en" suppressHydrationWarning>
			<body
				className={`antialiased h-screen`}
			>
			<ThemeProvider
				attribute="class"
				defaultTheme="system"
				enableSystem
				disableTransitionOnChange
			>
				<SidebarProvider>
					<Header/>
					{user &&
              <AppSidebar/>
					}
					<main className={'mt-20 w-full py-14 px-20 border'}>
					{children}
					<Toaster />
					</main>
				</SidebarProvider>
			</ThemeProvider>
			</body>
			</html>
		</>
	);
}
